CREATE TABLE [dbo].[BOT_INVESTMENT] (
    [BOT_INVESTMENT_ID]                   INT             IDENTITY (1, 1) NOT NULL,
    [BOT_INVESTMENT_CRYPTOCURRENCY]       NVARCHAR (MAX)  NOT NULL,
    [BOT_INVESTMENT_INVESTEDAMOUNT]       DECIMAL (18, 2) NOT NULL,
    [BOT_INVESTMENT_CRYPTOCURRENCYAMOUNT] DECIMAL (18, 2) NOT NULL,
    [BOT_INVESTMENT_DATE]                 DATETIME2 (7)   NOT NULL,
    [BOT_INVESTMENT_CURRENTVALUE]         DECIMAL (18, 2) NOT NULL,
    [BOT_INVESTMENT_ROI]                  DECIMAL (18, 2) NOT NULL,
    CONSTRAINT [PK_BOT_INVESTMENT] PRIMARY KEY CLUSTERED ([BOT_INVESTMENT_ID] ASC)
);

