CREATE TABLE [dbo].[GOT_CURRENCY_TYPE] (
    [GOT_CURRENCY_TYPE_ID]          INT            IDENTITY (1, 1) NOT NULL,
    [GOT_CURRENCY_TYPE_NAME]        NVARCHAR (MAX) NOT NULL,
    [GOT_CURRENCY_TYPE_PROGID]      NVARCHAR (MAX) NOT NULL,
    [GOT_CURRENCY_TYPE_DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    [GOT_CURRENCY_TYPE_ISACTIVE]    BIT            NOT NULL,
    CONSTRAINT [PK_GOT_CURRENCY_TYPE] PRIMARY KEY CLUSTERED ([GOT_CURRENCY_TYPE_ID] ASC)
);

