CREATE TABLE [dbo].[GOT_INVEST_PERIOD] (
    [GOT_INVEST_PERIOD_ID]          INT            IDENTITY (1, 1) NOT NULL,
    [GOT_INVEST_PERIOD_PROGID]      NVARCHAR (MAX) NOT NULL,
    [GOT_INVEST_PERIOD_NAME]        NVARCHAR (MAX) NOT NULL,
    [GOT_INVEST_PERIOD_DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    [GOT_INVEST_PERIOD_ISACTIVE]    BIT            NOT NULL,
    [GOT_INVEST_PERIOD_DAYS]        INT            NOT NULL,
    CONSTRAINT [PK_GOT_INVEST_PERIOD] PRIMARY KEY CLUSTERED ([GOT_INVEST_PERIOD_ID] ASC)
);

