// <auto-generated />
using System;
using CryptoDCA.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoDCA.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241016155247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptoDCA.DataModel.Context.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BOT_INVESTMENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CryptoValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BOT_INVESTMENT_CRYPTOCURRENCYAMOUNT");

                    b.Property<string>("Cryptocurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BOT_INVESTMENT_CRYPTOCURRENCY");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BOT_INVESTMENT_CURRENTVALUE");

                    b.Property<decimal>("InvestedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BOT_INVESTMENT_INVESTEDAMOUNT");

                    b.Property<DateTime>("InvestmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BOT_INVESTMENT_DATE");

                    b.Property<decimal>("ROI")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BOT_INVESTMENT_ROI");

                    b.HasKey("Id");

                    b.ToTable("BOT_INVESTMENT");
                });
#pragma warning restore 612, 618
        }
    }
}
